const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_URL?.includes('localhost') ? false : { rejectUnauthorized: true }
});

async function setupTables() {
  const client = await pool.connect();
  try {
    console.log('🔄 Ensuring ACCESS_REQUESTS and ADMIN_AUDIT_LOGS tables exist...');
    
    // 1. ACCESS_REQUESTS Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS "ACCESS_REQUESTS" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "username" VARCHAR(50) NOT NULL,
        "requested_role" VARCHAR(50) NOT NULL,
        "status" VARCHAR(20) DEFAULT 'PENDING',
        "reason" TEXT,
        "requested_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        "reviewed_at" TIMESTAMP WITH TIME ZONE,
        "reviewed_by" VARCHAR(50),
        "review_notes" TEXT
      );
    `);
    
    // 2. ADMIN_AUDIT_LOGS Table
    await client.query(`
      CREATE TABLE IF NOT EXISTS "ADMIN_AUDIT_LOGS" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "action" VARCHAR(100) NOT NULL,
        "target_type" VARCHAR(50),
        "target_id" VARCHAR(50),
        "actor" VARCHAR(50) NOT NULL,
        "details" JSONB,
        "ip_address" VARCHAR(50),
        "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    `);

    // Indexes
    await client.query(`CREATE INDEX IF NOT EXISTS "idx_access_requests_username_status" ON "ACCESS_REQUESTS"("username", "status");`);
    await client.query(`CREATE INDEX IF NOT EXISTS "idx_admin_audit_created_at" ON "ADMIN_AUDIT_LOGS"("created_at" DESC);`);

    // 3. User Table Security Columns (must_change_password)
    await client.query(`ALTER TABLE "axusers" ADD COLUMN IF NOT EXISTS "must_change_password" BOOLEAN DEFAULT FALSE;`);

    // 4. Expand legacy transport remarks column limits
    await client.query(`ALTER TABLE "CABBOOKING_DETAILS" ALTER COLUMN "REMARKS_APVR" TYPE TEXT;`);
    await client.query(`ALTER TABLE "CABBOOKING_DETAILS" ALTER COLUMN "REMARKS_USER" TYPE TEXT;`);

    // 5. Database-Level Audit Log Immutability Trigger (Phase H)
    await client.query(`
      CREATE OR REPLACE FUNCTION enforce_audit_log_immutability()
      RETURNS TRIGGER AS $$
      BEGIN
        RAISE EXCEPTION 'ADMIN_AUDIT_LOGS is append-only. UPDATE and DELETE operations are forbidden.'
          USING ERRCODE = '55000';
      END;
      $$ LANGUAGE plpgsql;

      DROP TRIGGER IF EXISTS trg_audit_log_immutability ON "ADMIN_AUDIT_LOGS";
      CREATE TRIGGER trg_audit_log_immutability
      BEFORE UPDATE OR DELETE ON "ADMIN_AUDIT_LOGS"
      FOR EACH ROW EXECUTE FUNCTION enforce_audit_log_immutability();
    `);

    const tables = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public'
      ORDER BY table_name;
    `);
    console.log('✅ Current public tables in Neon DB:');
    console.table(tables.rows);
  } catch (err) {
    console.error('❌ Table setup failed:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

setupTables();
